### ISSUE TITLE
There are garbled character when `run` task

### ISSUE THREAD

**Issue by scillidan** [biozz/sublime-taskfile#5]
I use [cmder](https://cmder.app) on Windows10, and when I run this Taskfile.yml:
```
version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
```

It report:
```
'task' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
[Finished in 54ms with exit code 1]
[shell_cmd: task hello]
[dir: D:\ketarin_src\taskfile]
[path: C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Tailscale IPN;C:\Users\scillidan\scoop\apps\ghostscript\current\lib;C:\Users\scillidan\scoop\apps\rustup\current\.cargo\bin;C:\Users\scillidan\scoop\apps\python\current\Scripts;C:\Users\scillidan\scoop\apps\python\current;C:\Users\scillidan\scoop\apps\nodejs\current\bin;C:\Users\scillidan\scoop\apps\nodejs\current;C:\Users\scillidan\go\bin;C:\Users\scillidan\scoop\apps\yarn\current\global\node_modules\.bin;C:\Users\scillidan\scoop\apps\yarn\current\bin;C:\Users\scillidan\scoop\apps\opencv\current\x64\vc14\bin;D:\bin\todo\target\debug;C:\Users\scillidan\scoop\apps\gsudo\current;C:\Users\scillidan\AppData\Roaming\Python\Python310\Scripts;D:\bin\waifu2x-ncnn-vulkan;D:\bin;C:\Users\scillidan\scoop\apps\cmder\current\vendor;D:\bin\nconvert;C:\Users\scillidan\scoop\shims;C:\Users\scillidan\AppData\Local\Microsoft\WindowsApps;c:\users\scillidan\.local\bin]
```

**Comment by biozz** [comment]
Hi @scillidan! I'm sorry, I don't have Windows machine and it is too much of a hassle launching a VM, so it is going to be hard to debug.

It might be one of the encoding issues specific to Windows, which I read about on Sublime forums.

Can you try adding these lines to your taskfile and show me the output of `task hello`?

```yaml
version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
      - echo $LC_CTYPE
      - echo $LANG
    silent: true
```

And please run it through your shell and not through Sublime and my plugin, otherwise I will not be able to read the output. :)
